### ISSUE TITLE
  How to specify the delay?

### ISSUE THREAD

**Issue by alewir** [testcontainers/moby-ryuk#17]
The readme says:
"project helps you to remove ... ... after specified delay"

Could you please provide an example how to specify the mentioned delay?

**Comment by mdelapenya** [comment]
Hi @alewir sorry for the radio silence, I'm taking care of triaging this repository since very recently, and I want to answer this question.

The specified delay was that Ryuk would die if no Docker connection happened in 60 seconds. Since #49, now it's possible to set the timeout using an environment variable when declaring the Ryuk instance (this could be specific to the lang you used to write your tests).

Hope it helps, and sorry again for taking too long to answer.

**Comment by mdelapenya** [comment]
With #64 and #49, all three configs can be done using an env var. I think we can close this one

Thanks!
